### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by d-alleyne** [PetterKraabol/Twitch-Chat-Downloader#26] opened 2017-12-26 12:56 UTC
I see the following error for all formats except JSON.

> return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f440' in position 43: character maps to <undefined>

**Comment by d-alleyne** [comment] 2017-12-26 14:19
I "fixed" it on Windows by backing up cp1252.py, and filling its contents with utf_8.py.

**Comment by PetterKraabol** [comment] 2017-12-26 20:31
Hi, this looks like an emoji issue. I ran the script on a Windows 10 VM and it worked just fine. Emojis are expectedly appearing as blocks and there are no errors.

Try using this branch https://github.com/PetterKraabol/Twitch-Chat-Downloader/tree/issue-26
I guess the error comes from printing the lines in your terminal/cmd, rather than writing them to disk.

**Comment by PetterKraabol** [comment] 2018-01-06 23:59
Closing this for now. Unable to reproduce the error in windows.

**Closed by PetterKraabol** 2018-01-06 23:59 UTC
Labels: bug
