### ISSUE TITLE
[bug] Timecode syntax error: second and millisecond truncated

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#3] opened 2017-03-03 18:38 UTC
I think either when the timecode is exactly a whole number or _>something else happens<_ then the parser truncates the trailing digits. This leads to a syntax error in _Media Player Classic - Home Cinema_ with SSA subtitle at least.

Twitch-Chat-Downloader commit hash of the version I'm using is e21c9d730ebdf4a8cd69d744bb0418868a20456d.

Here's an [example Twitch video](https://www.twitch.tv/videos/125972865), 125972865 (please don't judge, lol). Error occurs at line 221 in the SSA.

EDIT: Oh and MPC-HC also gives me a syntax error on the last line of the SSA subtitle, even though it looks perfectly fine.

**Comment by PetterKraabol** [comment] 2017-03-14 15:05
Fixed in 00c65cf1baaa5f3ca3e96d481c78371f2516b4a3

Btw, the ssa/ass subtitle styles look really bad atm. Try changing style settings in `settings.json`. From what I've seen, style rules don't seem to work as intended, at least not when I test colors and borders in VLC. If you find a format that looks good as a default, feel free to share it.

Check if MPC-HC gives you the same error if you remove the last empty line.

**Comment by PetterKraabol** [comment] 2017-03-15 16:42
I tried MPC-HC and it worked just fine with SSA. I'll close this for now.

**Closed by PetterKraabol** 2017-03-15 16:42 UTC
Labels: bug
